### ISSUE TITLE
Substance Painter save error

### ISSUE THREAD

**Issue by thomaspiot** [Wizard-collab/Wizard#52]
on est plusieurs à avoir des problèmes de sauvegarde avec substance
en gros quand on fait un save avec la shelf wizard le versioning se fait mais wizard ne le prend pas en compte

ex: on a notre fichier blabla.0006 dans le dossier substance mais dans wizard on est toujours à la version 0005

ça à l'air de le faire un peu avec tous les soft de façon aléatoire mais surtout avec substance apparemment
je sais pas si tu est déjà au courant ni d'où ça peut venir 

pour l'instant on règle le problème en suppriment la version N-1 et en renommant la version N en N-1

voilà

**Comment by Wizard-collab** [comment]
Problème reglé :)
